apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-client
spec:
  description: >-
    Runs oc commands against your OpenShift cluster using a specified image.
  params:
    - name: SCRIPT
      type: string
      description: The script to run
  steps:
    - name: oc
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/bin/sh
        $(params.SCRIPT)
